# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  pre = "<i class=\"fas fa-images\"></i>"
  name = "Screenshots"
  url = "screenshots"
  weight = 10

[[main]]
  pre = "<i class=\"fas fa-keyboard\"></i>"
  name = "Shortcuts"
  url = "shortcuts"
  weight = 20

[[main]]
  pre = "<i class=\"fas fa-terminal\"></i>"
  name = "Commands"
  url = "commands"
  weight = 30

[[main]]
  pre = "<i class=\"fas fa-newspaper\"></i>"
  name = "Changelog"
  url = "https://github.com/crow-translate/crow-translate/blob/master/CHANGELOG.md"
  weight = 40
  
[[main_right]]
  name = "<i class=\"fas fa-globe-americas\"></i>"
  post = "Transifex"
  url = "https://www.transifex.com/crow-translate/crow-translate/dashboard/"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-github-alt\"></i>"
  post = "GitHub"
  url = "https://github.com/crow-translate"
  weight = 20

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
